---

- hosts: all
  become: true
#  remote_user: root
  vars:
    first_initial: r
    last_name: race
    username: "{{ first_initial }}{{ last_name }}"
    new_net_connection_name: ansible_eth1
    new_net_connection_type: ethernet
    new_net_connection_ip: 10.0.0.10
    new_net_connection_cidr: /24
    new_net_connection_gw: 10.0.0.1
    new_net_connection_dns: 8.8.8.8

  tasks:
  - include: tasks/network_cfg.yml
  - include: tasks/ntp_cfg.yml

#Create and Configure User################################
  - name: Create User
    user:
      name: "{{ username }}"
      shell: /bin/bash
      createhome: yes
      append: yes
  - name: Add user to sudoers
    command: /usr/bin/touch /tmp/ansible_sudoer.text
###########################################################
  - name: Configure SSH with Certificates
    command: /usr/bin/touch /tmp/ansible_ssh.text
  - name: Add notice-levl syslog file
    command: /usr/bin/touch /tmp/ansible_log_create.text
  - name: log Ansible Configuration
    command: /usr/bin/touch /tmp/ansible_log.text
