---

- hosts: all
#  remote_user: root
  vars:
    first_initial: r
    last_name: race
    username: "{{ first_initial }}{{ last_name }}"
    new_net_connection_name: ansible_eth1
    new_net_connection_type: ethernet
    new_net_connection_ip: 10.0.0.10
    new_net_connection_gw: 10.0.0.1
    new_net_connection_dns: 8.8.8.8

  tasks:
#Required install for working NetworkManager through Ansible
  - name: Verify NetworkManager libraries are installed
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - NetworkManager-glib
    become: true
#Set Network Interface######################################
  - name: Configure Static IP For Redhat Based Systems
    nmcli:
      conn_name: "{{ new_net_connection_name }}"
      ifname: "{{ ansible_default_ipv4.interface }}"
      type: "{{ new_net_connection_type }}"
      ip4: "{{ new_net_connection_ip }}"
      gw4: "{{ new_net_connection_gw }}"
      state: present
    become: true
    when: ansible_os_family == "RedHat" #This command is only applicable to RedHat based systems
#Set DNS in newly created interface
  - name: Set DNS
    nmcli:
      conn_name: "{{ new_net_connection_name }}"
      type: "{{ new_net_connection_type }}"
      dns4: "{{ new_net_connection_dns }}"
      state: present
    become: true
    when: ansible_os_family == "RedHat"  #This command is only applicable to RedHat based systems
  - name: Restart Network Interface
    command: /usr/sbin/ifup ifcfg-"{{ new_net_connection_name}}"
    become: true
#Set NTP##################################################
  - name: Install NTP
    yum: name=ntp state=installed
    become: true
  - name: Configure NTP
    template: src=ntp.conf.j2 dest=/etc/ntp.conf
    become: true
  - name: Start and Enable NTP
    service: name=ntpd state=started enabled=yes
    become: true
#Create and Configure User################################
  - name: Create User
    user:
      name: "{{ username }}"
      shell: /bin/bash
      createhome: yes
      append: yes
    become: true
  - name: Add user to sudoers
    command: /usr/bin/touch /tmp/ansible_sudoer.text
###########################################################
  - name: Configure SSH with Certificates
    command: /usr/bin/touch /tmp/ansible_ssh.text
  - name: Add notice-levl syslog file
    command: /usr/bin/touch /tmp/ansible_log_create.text
  - name: log Ansible Configuration
    command: /usr/bin/touch /tmp/ansible_log.text
