---
#configure ssh for user
# - name: Create ssh keys for defined user
#   user:
#     name: "{{ username }}"
#     generate_ssh_key: yes
#
# - name: Copy generated public key
#   command: cp /home/{{ username }}/.ssh/id_rsa.pub /tmp/{{ username }}_id_rsa.pub

# - name: Copy generated public key
#   copy:
#     src: /home/{{ username }}/.ssh/id_rsa.pub
#     dest: /tmp/{{ username }}_id_rsa.pub

- name: Add the authorized_key to the user "{{ username }}"
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_key }}" #"{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"
