---
#Configure SSH on the remote machine to deny root logins and require key authentication.
#config file needs to be located in the files directory
- name: Configure SSHD
  template: src=files/sshd_config.j2 dest=/etc/ssh/sshd_config

- name: Restart
  service:
    name: sshd
    state: restarted
